import Head from 'next/head'
import Image from 'next/image'
import {Geist, Geist_Mono} from 'next/font/google'
import MdxLexer from '../../components/MarkdownLexer.js'
import styles from '@/styles/Home.module.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export default function Home() {
  const mdx = [
    '```md',
    '## Sample Markdown ',
    '<!-- js:index.js -->',
    'function sample() {',
    '  return <></>;',
    '}',
    '',
    '<!-- css:main.css -->',
    'body {',
    '  color: red;',
    '}',
    '```'
  ].join('\n')
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <MdxLexer mdxString={mdx} />
        </main>
      </div>
    </>
  )
}
