name: release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "The semver to use"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
      tag:
        description: "The npm tag"
        required: false
        default: "latest"
      commit-message:
        description: "The commit message template"
        required: false
        default: "chore(release): {version}"
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      COMMIT_MESSAGE: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.commit-message || 'chore(release): {version}' }}
      SEMVER: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.semver || 'patch' }}
      NPM_TAG: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || 'latest' }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install
      - name: Build package
        run: npm run build
      - name: Publish to npm
        uses: nearform/optic-release-automation-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          commit-message: ${{ env.COMMIT_MESSAGE }}
          semver: ${{ env.SEMVER }}
          npm-tag: ${{ env.NPM_TAG }}
